services:
  dependencies:
    container_name: dependencies
    build:
      dockerfile: Dockerfile
      target: dependencies
    working_dir: /home/lib
    volumes:
      - ./:/home/lib:consistent
  node:
    container_name: node
    depends_on:
      dependencies:
        condition: service_completed_successfully
    build:
      dockerfile: Dockerfile
      target: node
    working_dir: /home/lib
    volumes:
      - ./:/home/lib:consistent
    tty: true
