export const SYMBOL_MODEL_PROP_PENDING = Symbol('foscia:pending prop');
export const SYMBOL_MODEL_PROP_ID: unique symbol = Symbol('foscia:id prop');
export const SYMBOL_MODEL_PROP_ATTRIBUTE: unique symbol = Symbol('foscia:attr prop');
export const SYMBOL_MODEL_PROP_RELATION: unique symbol = Symbol('foscia:rel prop');
export const SYMBOL_MODEL_RELATION_HAS_ONE: unique symbol = Symbol('foscia:rel has one');
export const SYMBOL_MODEL_RELATION_HAS_MANY: unique symbol = Symbol('foscia:rel has many');
export const SYMBOL_MODEL_CLASS: unique symbol = Symbol('foscia:model');
export const SYMBOL_MODEL_INSTANCE: unique symbol = Symbol('foscia:instance');
export const SYMBOL_MODEL_COMPOSABLE: unique symbol = Symbol('foscia:composable');
