blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/foscia-dev/foscia/discussions/new?category=q-a
    about: Ask a question or discuss about Foscia
  - name: Ideas
    url: https://github.com/foscia-dev/foscia/discussions/new?category=ideas
    about: Start a discussion to improve Foscia
