/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import typedocSidebar from './docs/api/typedoc-sidebar.cjs';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'doc',
      label: 'About',
      id: 'about',
    },
    {
      type: 'doc',
      label: 'Installing',
      id: 'installing',
    },
    {
      type: 'category',
      label: 'Upgrading',
      items: [{
        type: 'autogenerated',
        dirName: 'upgrading',
      }],
      link: {
        type: 'generated-index',
        title: 'Upgrading',
        description: 'Upgrade guides, support policy and full changelog.',
        slug: '/category/upgrading',
      },
    },
    {
      type: 'doc',
      label: 'Getting started',
      id: 'getting-started',
    },
    {
      type: 'category',
      label: 'Core concepts',
      collapsed: false,
      items: [{
        type: 'autogenerated',
        dirName: 'core-concepts',
      }],
      link: {
        type: 'generated-index',
        title: 'Core concepts',
        description: 'Learn more about the core concepts of Foscia.',
        slug: '/category/core-concepts',
      },
    },
    {
      type: 'category',
      label: 'Digging deeper',
      items: [{
        type: 'autogenerated',
        dirName: 'digging-deeper',
      }],
      link: {
        type: 'generated-index',
        title: 'Digging deeper',
        description: 'Learn advanced capabilities of Foscia.',
        slug: '/category/digging-deeper',
      },
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{
        type: 'autogenerated',
        dirName: 'integrations',
      }],
      link: {
        type: 'generated-index',
        title: 'Integrations',
        description: 'Integrate Foscia with other frameworks and tools.',
        slug: '/category/integrations',
      },
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
        {
          type: 'link',
          label: 'Foscia playgrounds',
          description: 'Try Foscia in multiple StackBlitz playgrounds.',
          href: '/playgrounds',
        },
        {
          type: 'link',
          label: 'Foscia examples',
          description: 'GitHub repository containing examples of projects using Foscia.',
          href: 'https://github.com/foscia-dev/foscia-examples',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Examples',
        description: 'Learn how to use Foscia using concrete examples.',
        slug: '/category/examples',
      },
    },
    {
      type: 'category',
      label: 'API',
      items: typedocSidebar,
      link: {
        type: 'generated-index',
        title: 'API',
        description: 'API reference of each packages.',
        slug: '/category/api',
      },
    },
    {
      type: 'category',
      label: 'Help',
      items: [
        {
          type: 'doc',
          label: 'FAQ',
          id: 'help/faq',
        },
        {
          type: 'link',
          label: 'Support',
          href: 'https://github.com/foscia-dev/foscia/issues',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Help',
        description: 'Get help or learn more on Foscia.',
        slug: '/category/help',
      },
    },
  ],
};

module.exports = sidebars;
