/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import typedocSidebar from './docs/reference/api/typedoc-sidebar.cjs';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'doc',
      label: 'About',
      id: 'about',
    },
    {
      type: 'doc',
      label: 'Installation',
      id: 'installation',
    },
    {
      type: 'category',
      label: 'Upgrade',
      items: [{
        type: 'autogenerated',
        dirName: 'upgrade',
      }],
      link: {
        type: 'generated-index',
        title: 'Upgrade',
        description: 'Upgrade guides and full changelog.',
        slug: '/category/upgrade',
      },
    },
    {
      type: 'doc',
      label: 'Getting started',
      id: 'getting-started',
    },
    {
      type: 'category',
      label: 'Core concepts',
      collapsed: false,
      items: [{
        type: 'autogenerated',
        dirName: 'core-concepts',
      }],
      link: {
        type: 'generated-index',
        title: 'Core concepts',
        description: 'Learn more about the core concepts of Foscia.',
        slug: '/category/core-concepts',
      },
    },
    {
      type: 'category',
      label: 'Digging deeper',
      items: [{
        type: 'autogenerated',
        dirName: 'digging-deeper',
      }],
      link: {
        type: 'generated-index',
        title: 'Digging deeper',
        description: 'Learn advanced capabilities of Foscia.',
        slug: '/category/digging-deeper',
      },
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
        {
          type: 'link',
          label: 'Foscia playground',
          description: 'Try Foscia with Typescript, Vue and React.',
          href: '/playground',
        },
        {
          type: 'link',
          label: 'Foscia examples',
          description: 'GitHub repository containing examples of projects using Foscia.',
          href: 'https://github.com/foscia-dev/foscia-examples',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Examples',
        description: 'Learn how to use Foscia using concrete examples.',
        slug: '/category/examples',
      },
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'doc',
          id: 'reference/models-utilities',
        },
        {
          type: 'doc',
          id: 'reference/actions-enhancers',
        },
        {
          type: 'doc',
          id: 'reference/actions-runners',
        },
        {
          type: 'doc',
          id: 'reference/actions-extensions',
        },
        {
          type: 'category',
          label: 'Implementations',
          items: [{
            type: 'autogenerated',
            dirName: 'reference/implementations',
          }],
          link: {
            type: 'generated-index',
            title: 'Implementations and configuration',
            slug: '/category/implementations',
          },
        },
        {
          type: 'category',
          label: 'API',
          description: 'GitHub repository containing examples of projects using Foscia.',
          items: typedocSidebar,
        },
      ],
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Functions documentation and API reference.',
        slug: '/category/reference',
      },
    },
    {
      type: 'category',
      label: 'Help',
      items: [
        {
          type: 'doc',
          label: 'FAQ',
          id: 'help/faq',
        },
        {
          type: 'link',
          label: 'Support',
          href: 'https://github.com/foscia-dev/foscia/issues',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Help',
        description: 'Get help or learn more on Foscia.',
        slug: '/category/help',
      },
    },
  ],
};

module.exports = sidebars;
