name: deploy
run-name: "deploy ${{ inputs.target }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      alias:
        type: choice
        description: Choose release
        required: true
        options:
          - production
          - staging
          - dev
  workflow_call:
    inputs:
      alias:
        type: string
        required: true
      pull:
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Pull
        if: ${{ inputs.pull }}
        run: git pull

      - name: Install
        run: pnpm install

      - name: Prepare env
        if: ${{ inputs.alias != 'production' }}
        run: |
          touch website/.env
          echo "VERSION=${{ inputs.alias }}" >> website/.env

      - name: Build
        run: pnpm build && pnpm --filter=website build

      - name: Install Netlify
        run: pnpm add -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --filter @foscia/website \
            --dir website/build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            ${{ inputs.alias == 'production' && '--prod' || format('--alias {0}', inputs.alias) }}
