name: deploy
run-name: "deploy ${{ github.event.inputs.prod == 'true' && 'prod ' || 'next ' }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      prod:
        type: boolean
        description: Production deploy
        default: false
  workflow_call:
    inputs:
      prod:
        type: boolean
        description: Production deploy
        default: false

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build && pnpm --filter=website build

      - name: Install Netlify
        run: pnpm add -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --filter @foscia/website \
            --dir website/build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            ${{ github.event.inputs.prod == 'true' && '--prod' || '--alias next' }}
