name: tests

on: [ push, pull_request ]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: make docker-build

      - name: Test
        run: make test

      - name: Coverage upload
        uses: codecov/codecov-action@v4
        with:
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    if: github.event_name == 'push' && github.repository_owner == 'foscia-dev' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next')
    name: Deploy website
    needs: [ test ]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      alias: 'dev'
      pull: true
